name: task_management_app
description: A dynamic task management app with Google Sign-In and task handling.

# The version of your application
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Google Sign-In
  google_sign_in: ^5.4.0

  # Date and time pickers
  intl: ^0.18.0

  # To use icons
  flutter_svg: ^1.1.6

  # For animations
  flutter_animate: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
